try:
 y = test
except:
 print("Bu nameError")

 # Errorni ko'rmoqchi bolsangiz try va exceptni o'chiring !